### ISSUE TITLE
there is a error when I make it

### ISSUE THREAD

**Issue by xionglihua** [aliyun/alibabacloud-nls-cpp-sdk#1]
The error is happened at the link mement, as shows follows: 
/nls-sdk-cpp-master/lib/linux/libssl.so: file format not recognized; treating as linker script
/nls-sdk-cpp-master/lib/linux/libssl.so:1: syntax error

**Comment by soildierKing** [comment]
the libssl.so is a 64-bit library compiled with GCC 4.1.2. please check the gcc version.
