### ISSUE TITLE
C#接口调用SetOutputFormat无法设置文本

### ISSUE THREAD

**Issue by zhanghua003** [aliyun/alibabacloud-nls-cpp-sdk#13]
st.stPtr.SetOutputFormat(st.stPtr, "EUC-KR");
通过上述代码设置韩语，显示任然的乱码，SetOutputFormat的参数有对应的字典集吗

**Comment by season4675** [comment]
> st.stPtr.SetOutputFormat(st.stPtr, "EUC-KR"); 通过上述代码设置韩语，显示任然的乱码，SetOutputFormat的参数有对应的字典集吗

如SetOutputFormat的接口说明，只能设置UTF8和GBK。这是设置返回结果的编码，若发现乱码，可确认下返回结果的编码和系统显示的编码是否符合。
