### ISSUE TITLE
SDK的版本关系

### ISSUE THREAD

**Issue by hailiang-wang** [aliyun/alibabacloud-nls-cpp-sdk#2]
请问这个github项目和下面文档所提供的SDK下载地址内的SDK是对应的么？

https://help.aliyun.com/document_detail/84569.html?spm=a2c4g.11186623.6.575.a1e17fb0jh7lQc

在上面链接中，得到的SHARED Libs，考虑到集成到我们产品的构建系统，使用SDK的源码编译更友好。

**Comment by bincard** [comment]
阿里云官网上提供的SDK版本是最新的，建议用户尽量使用官网版本。
针对有某些原因不能使用官网版本的用户，可以参考此开源版本的SDK中鉴权和协议交互逻辑自行对接。

**Comment by hailiang-wang** [comment]
官网的SDK是Shared Lib, 而且需要整个项目使用 CXXFLAGS "-D_GLIBCXX_USE_CXX11_ABI=0 -fPIC" 编译项目，这样并不友好，建议发布源码，这样可以灵活的让C++用户集成到自己项目中。
