### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by burne-muz** [aliyun/alibabacloud-nls-cpp-sdk#4]
make[2]: *** No rule to make target 'common/jsoncpp-prefix/lib/libjsoncpp.a', needed by 'lib/libalibabacloud-idst-speech.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:421: nlsCppSdk/CMakeFiles/alibabacloud-idst-speech.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
在Debian 10环境下，执行./build_linux.sh时失败。

**Comment by season4675** [comment]
> make[2]: *** No rule to make target 'common/jsoncpp-prefix/lib/libjsoncpp.a', needed by 'lib/libalibabacloud-idst-speech.so'. Stop. make[1]: *** [CMakeFiles/Makefile2:421: nlsCppSdk/CMakeFiles/alibabacloud-idst-speech.dir/all] Error 2 make: *** [Makefile:130: all] Error 2 在Debian 10环境下，执行./build_linux.sh时失败。

https://github.com/aliyun/alibabacloud-nls-cpp-sdk/issues/6#issuecomment-902369689
可以看看这里的解决方法，本质是没找到libjsoncpp.a，可以手动改下编译文件进行解决。 当然，此问题已经在新分支sdk_3.1解决。
