### ISSUE TITLE
speechTranscriberRequest.sendAudio返回0

### ISSUE THREAD

**Issue by wenfer** [aliyun/alibabacloud-nls-cpp-sdk#5]
2.0版本的入参是char*  3.0是uint8_t*    我直接把数据转成uint8_t*后，sendAudio返回0，不知道算成功还是失败

**Comment by huangwenrong** [comment]
同样的问题，用freeswitch 可以正常使用2.0版本，用3.0 改成uint8_t 返回的是0，帮忙看看是哪里有需要特殊处理吗？

**Comment by season4675** [comment]
> 同样的问题，用freeswitch 可以正常使用2.0版本，用3.0 改成uint8_t 返回的是0，帮忙看看是哪里有需要特殊处理吗？

非负则为成功，无需处理

**Comment by season4675** [comment]
> 2.0版本的入参是char* 3.0是uint8_t* 我直接把数据转成uint8_t*后，sendAudio返回0，不知道算成功还是失败

非负则为成功，无需处理
