### ISSUE TITLE
在arm-linux下，编译不成功

### ISSUE THREAD

**Issue by codenot** [aliyun/alibabacloud-nls-cpp-sdk#7]
libalibabacloud-idst-common.so 有arm版本么？ 能不能支持下arm-linux?

**Comment by season4675** [comment]
> libalibabacloud-idst-common.so 有arm版本么？ 能不能支持下arm-linux?

暂时不提供sdk_3.0版本 arm版本libalibabacloud-idst-common.so的提供。可使用sdk_3.1分支进行交叉编译。
